### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by amiracam** [iconara/puck#33]
sorry for the intrusion, just thought I ask for your perspective
I'm trying to get away from the use of Warbler and its deployment intoJava app servlet containers such as Jetty

I have a Sinatra app for which I have currently defined a config.ru again packed to run in Jetty by Warbler but instead I want to explore running Puma , from checking out your code it seems then that the config.ru  is irrelevant but rather the starting endpoint should be something like your server script i.e.

#!/usr/bin/env ruby

$LOAD_PATH << File.expand_path('../../lib', __FILE__)

require 'rack/handler/puma'
require 'example_app/hello_world'

config_path = File.expand_path('../../config/app.yml', __FILE__)
config = YAML.load_file(config_path)
port = config['port'].to_i
app = ExampleApp::HelloWorld.new(File.basename($0) + ": " + config['message'])
Rack::Handler::Puma.run(app, :Port => port)

I also will then assume that somewhere in the packaging thru Puma you specify this file to be your start point and thus I will scan your repo to glean how that is setup?

Am I missing something ? any words of advice to facilitate are appreciated.

Finally, thank you for writing this potentially very useful utility.

**Comment by iconara** [comment]
Short answer is yes, stick the script you posted in a file, put it in `bin/`, package with Puck, and run it with `java -jar build/app-name.jar bin-script-name`. It won't do much more than the same script would do if you run it without packaging, all Puck does is making sure the jar file has all dependencies bundled into it.

**Comment by amiracam** [comment]
Thank you very much for the quick feedback

Charles A. Monteiro
Chief Technology Officer
Datasoft, Inc
Phone: 347-853-7349
tradeblazer.com

**Comment by amiracam** [comment]
hi, got back to this issue and because of the manner we deploy I was wondering if there was a way of embedding the script as opposed to passing to java upon the jar invocation i.e. more like the notion of having a "main class" or specified entry point 

I could not find anything within the docs that alluded to this but thought I ask

thanks again

**Comment by iconara** [comment]
I don't think I ever made a feature like that for Puck, but it's possible to do. The way Puck works is that it uses a not-very-documented feature of JRuby. Setting the main class of a jar to `org.jruby.JarBootstrapMain` means that when the jar is run with `java -jar …` the file `jar-bootstrap.rb` in the root of the jar gets executed.

You can see what Puck adds to that file here: https://github.com/iconara/puck/blob/e21669f03ccdca80bc4e6c1f8fee6a4afd94e8af/lib/puck/jar.rb#L184-L195

You could, in theory, package an app with Puck, and then replace that file with something very similar but that started your application without the need to specify the name of a bin-script.

**Comment by amiracam** [comment]
once again , thank you
